name: CI-CD-Actions
env:
  EB_PACKAGE_S3_BUCKET_NAME: "troyanawsactions"
  EB_APPLICATION_NAME: "MyAPP"
  EB_ENVIRONMENT_NAME: "MyAPP-env"
  DEPLOY_PACKAGE_NAME: "my_app_${{github.sha }}.zip"

on:
  push:
    branches: 
      - main
      
jobs:
  ci_part:
    runs-on: ubuntu-latest
    
    steps:
    - name: git clone repo
      uses: actions/checkout@v1
      
    - name: Create package
      run: zip -r ${{env.DEPLOY_PACKAGE_NAME}} ./ -x *.git*
      
    - name: AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id       : ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key   : ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region              : ${{secrets.AWS_DEFAULT_REGION}}
        
        
    - name: Copy deployment
      run: aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/
      
    - name: The end
      run: echo "CI Part has been done"
    

  
  
