name: CI-CD-Actions
env:
  EB_PACKAGE_S3_BUCKET_NAME: "troyanawsactions"
  EB_APPLICATION_NAME: "MyAPP"
  EB_ENVIRONMENT_NAME: "MyAPP-env"
  DEPLOY_PACKAGE_NAME: "my_app_${{github.sha }}.zip"

on:
  push:
    branches: 
      - main
      
jobs:
  ci_part:
  #  runs-on: ubuntu-latest
    runs-on: actions-runner
    steps:
    - name: git clone repo
      uses: actions/checkout@v1
      
    - name: Create package
      run: zip -r ${{env.DEPLOY_PACKAGE_NAME}} ./ -x *.git*
      
    - name: AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id       : ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key   : ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region              : ${{secrets.AWS_DEFAULT_REGION}}
        
        
    - name: Copy deployment
      run: aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/
      
    - name: The end
      run: echo "CI Part has been done"
      
  cd_part:
    runs-on: ubuntu-latest
    needs: [ci_part]
    
    
    steps:
    - name: AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id       : ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key   : ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region              : ${{secrets.AWS_DEFAULT_REGION}}
        
    #- name: Create Beanstalk APK
     # run: |
      #  aws elasticbeanstalk create-application-version \
       # --application-name ${{ env.EB_APPLICATION_NAME }} \
        #--source-bundle S3Bucket="${{ env.EB_PACKAGE_S3_BUCKET_NAME }}",S3Key="${{ env.DEPLOY_PACKAGE_NAME }}" \
        #--version-label "Ver-${{ github.sha }}" \
        #--description "CommitSHA-${{ github.sha }}"
        
    - name: Update Beanstalk APK
      run: aws elasticbeanstalk update-environment  --environment-id "e-4usykcmz6v" --version-label "Ver-${{ github.sha }}"
      
    - name: Finish!!!!!
      run: echo "Finish!!!!!"
      
    

  
  
